### ISSUE TITLE
INVERTER COLLEGATO TRAMITE SCHEDA LAN E NON WIFI

### ISSUE THREAD

**Issue by GITHUBANDE** [sdesalve/zcsazzurro#1]
Buongiorno.
Ho un inverter collegato in rete tramite "Stick logger (ethernet) e non wifi.
Nel valore "authkey", cosa devo impostare?

**Comment by murraythegoz** [comment]
Anche io ho l'inverter collegato via cavo.
L'authkey è la medesima che via wifi.
