### ISSUE TITLE
3.0.1 Ok con Home assistant, ma problemi con postman

### ISSUE THREAD

**Issue by Corrado56** [sdesalve/zcsazzurro#11]
Per prima cosa confermo che con la versione 3.0.1 Home assistant ha ripreso a funzionare.
Ma non mi funziona più POSTMAN
Chiedo quindi ospitalità.... sperando che aturri legga:

Definito il nuovo header:
![image](https://user-images.githubusercontent.com/10588158/176934078-79f04f2a-202a-4d29-95ed-39b32950f0e4.png)
la connessione viene autenticata, ma questa semplice chiamata, che il 16/05 funzionava, adesso non funziona più
![image](https://user-images.githubusercontent.com/10588158/176934812-6d1eae40-5643-4e05-887f-c4969a1e574f.png)

@aturri vedo che usi postman per i test. Puoi per favore pubblicare il body di una chiamata che a te va bene.

Grazie
Corrado

**Comment by aturri** [comment]
Ciao @Corrado56,
il payload che uso via Postman è il seguente:
`{
    "realtimeData": {
        "command": "realtimeData",
        "params": {
            "thingKey": "ZAXXXXXXXXXX",
            "requiredValues": "*"
        }
    }
}`

Il comando `lastUpdated` non funziona più neanche a me...
Andrea

**Comment by Corrado56** [comment]
>> Il comando lastUpdated non funziona più neanche a me... 
Ok, grazie, non sono pazzo...

Ve ne mostro un'altra 
Questa è la situazione stamattina verso le 11 di stamattina, con un ritardo enorme nell'aggiornamento:
![image](https://user-images.githubusercontent.com/10588158/177033889-d243a770-9e31-474b-a5db-5d46469640d4.png)
mentre l'app Azzurro nel cellulare riporta dati aggiornati.
![image](https://user-images.githubusercontent.com/10588158/177034373-107e652b-31bc-4d92-b5ae-252d65d100d1.png)

Siamo diventati cittadini di serie B ?

**Comment by Corrado56** [comment]
> Ciao @Corrado56, il payload che uso via Postman è il seguente: `{ "realtimeData": { "command": "realtimeData", "params": { "thingKey": "ZAXXXXXXXXXX", "requiredValues": "*" } } }`
> 
> Il comando `lastUpdated` non funziona più neanche a me... Andrea

@aturri 

utilizzando il tuo payload, che funziona, ho notato che "lastUpdated" è finito nei realtime data, mentre prima era a parte
![image](https://user-images.githubusercontent.com/10588158/177035202-008fd0c6-aca8-4fe7-96c2-2de8c6b5d873.png)
aggiornato ad 8 ore fa...

Quindi in conclusione abbiamo manuale vs. 1.1 non aggiornato, e server in condizioni disperate.
La situazione non può che migliorare, ...
Mando una mail al supporto

**Comment by aturri** [comment]
Ciao @Corrado56,
Confermo che anche a me l'ultimo aggiornamento ricevuto da API è intorno al tuo stesso orario, mentre da portale Azzurro ci sono i dati aggiornati.
Fammi sapere poi cosa rispondono dal supporto tecnico.

grazie
Andrea

**Comment by sdesalve** [comment]
> Per prima cosa confermo che con la versione 3.0.1 Home assistant ha ripreso a funzionare. Ma non mi funziona più POSTMAN Chiedo quindi ospitalità.... sperando che aturri legga:
> 
> Definito il nuovo header: ![image](https://user-images.githubusercontent.com/10588158/176934078-79f04f2a-202a-4d29-95ed-39b32950f0e4.png) la connessione viene autenticata, ma questa semplice chiamata, che il 16/05 funzionava, adesso non funziona più ![image](https://user-images.githubusercontent.com/10588158/176934812-6d1eae40-5643-4e05-887f-c4969a1e574f.png)
> 
> @aturri vedo che usi postman per i test. Puoi per favore pubblicare il body di una chiamata che a te va bene.
> 
> Grazie Corrado

uso https://reqbin.com/ per i test. non ho provato con il nuovo header per mancanza dei dati di auth...

**Comment by Corrado56** [comment]
Il supporto non ha ancora risposto, ma dalle 10 di stamattina le api si aggiornano agni 15/20 minuti

**Comment by Corrado56** [comment]
E questa è la risposta del supporto, che non capisco:
se il wifi non dialogasse, nessun sistema dovrebbe aggiornarsi.

----------
Buonasera,
molto probabilmente il dispositivo wifi dell'inverter non sta più dialogando con il router di casa.
Di seguito il link dove può reperire la guida rapida e il video tutorial per la configurazione della scheda wifi 
https://www.zcsazzurro.com/it/documentazione/monitoring-systems-2

Per qualsiasi chiarimento siamo a sua disposizione.
