### ISSUE TITLE
Codes

### ISSUE THREAD

**Issue by luca320** [sdesalve/zcsazzurro#12]
thingkey: [YOUR DEVICE SERIAL - THINGKEY]
    authkey: [YOUR AUTHORIZATION HEADER VALUE]
    clientcode: [YOUR CLIENT CODE HERE]  

I have to use [abcdefghilm] or 'abcdefghilm' or abcdefghilm when I write the thingkey, authkey and clientcode?

Thank you

**Comment by sdesalve** [comment]
thingkey: 'aaaaaaaaaa'
authkey: 'bbbbbbbbb'
clientcode: 'ccccccccc'

However hassio should recognize JSON and validate if it was correctly typed

**Comment by luca320** [comment]
Ciao! Ho seguito e copiato tutto, ricontrollato 100 volte ma continua ad uscirmi errore e avvertenza…



Inviato da iPhone

**Comment by luca320** [comment]
Il giorno gio 21 lug 2022 alle ore 16:42 sdesalve ***@***.***>
ha scritto:

**Comment by sdesalve** [comment]
Che errore?

**Comment by luca320** [comment]
questo warning:
2022-07-22 12:48:17 WARNING (MainThread)
[custom_components.zcsazzurro.sensor] REST result could not be parsed as
JSON
e a volte questo errore in foto allegata.

tutte le entità sono non disponibili ahimè, ma la configurazione è valida


Il giorno ven 22 lug 2022 alle ore 12:42 sdesalve ***@***.***>
ha scritto:

**Comment by sdesalve** [comment]
Attiva i log debug per il rest. Cerca negli issue

Ma comunque sono i server che rispondono in maniera non corretta

**Comment by luca320** [comment]
A quanto pare a me non rispondono proprio, altro che non corretta.
inserisco questo in configuration.yaml
logger: default: error logs: homeassistant.components.rest: debug
homeassistant.components.rest.data: debug custom_components.zcsazzurro:
debug custom_components.zcsazzurro.sensor: debug

Nel mio configuration.yaml ho iniziato copiato il tuo codice e messo sotto
a sensor:

sensor:
  - platform: command_line
    name: Temperatura CPU
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'
    scan_interval: 10

  - platform: pirateweather
    api_key: X8Ey***********8YFJ2u8c4p6P
    scan_interval: '00:15:00'
    monitored_conditions:
    - apparent_temperature
    - apparent_temperature_high
    - apparent_temperature_low
    - cloud_cover
    - daily_summary
    - dew_point
    - hourly_summary
    - humidity
    - minutely_summary
    - moon_phase
    - ozone
    - precip_accumulation
    - precip_intensity
    - precip_intensity_max
    - precip_probability
    - precip_type
    - pressure
    - summary
    - temperature
    - temperature_high
    - temperature_low
    - uv_index
    - visibility
    - wind_bearing
    - wind_speed

  - platform: zcsazzurro
    name: fotovoltaico
    thingkey: 'ZM2E****1T747'
    authkey: 'Zcs eHWA****YO0'
    clientcode: 'Lucab*****di'

  - platform: integration
    name: power_generating_spent_zcs
    source: sensor.power_generating_zcs
    unit_prefix: k
    round: 2
    method: left

Il giorno ven 22 lug 2022 alle ore 12:55 sdesalve ***@***.***>
ha scritto:

**Comment by luca320** [comment]
2022-07-22 13:09:37 DEBUG (MainThread) [homeassistant.components.rest.data]
Updating from https://third.zcsazzurroportal.com:19003
2022-07-22 13:09:37 DEBUG (MainThread)
[custom_components.zcsazzurro.sensor] Data fetched from resource: INVALID
CLIENT
2022-07-22 13:09:37 WARNING (MainThread)
[custom_components.zcsazzurro.sensor] REST result could not be parsed as
JSON
2022-07-22 13:09:37 DEBUG (MainThread)
[custom_components.zcsazzurro.sensor] Erroneous JSON: INVALID CLIENT
2022-07-22 13:09:37 DEBUG (MainThread)
[custom_components.zcsazzurro.sensor] Return the state: False

Il giorno ven 22 lug 2022 alle ore 12:55 sdesalve ***@***.***>
ha scritto:

**Comment by sdesalve** [comment]
Invalid client...

**Comment by luca320** [comment]
2022-07-22 13:18:51 DEBUG (MainThread) [homeassistant.components.rest.data]
Updating from https://third.zcsazzurroportal.com:19003
2022-07-22 13:18:52 DEBUG (MainThread)
[custom_components.zcsazzurro.sensor] Data fetched from resource:
{"realtimeData": {"params": {"value": [{"ZM2ES060N1T747":
{"energyConsuming": 4.53, "energyGenerating": 6.3, "energyConsumingTotal":
292.4, "powerAutoconsuming": 696, "energyAutoconsumingTotal": 132.9,
"powerImporting": 0, "thingFind": "2022-07-21T15:36:28Z",
"energyDischarging": 2.77, "energyChargingTotal": 140.9,
"powerDischarging": 0, "batterySoC": 84, "powerExporting": 0,
"energyImportingTotal": 10.5, "energyGeneratingTotal": 273.8,
"energyCharging": 4.68, "lastUpdate": "2022-07-22T08:38:27Z",
"powerGenerating": 3456, "energyImporting": 0.14, "energyDischargingTotal":
149.0, "energyExportingTotal": 0.0, "powerCharging": 2760,
"powerConsuming": 696, "energyExporting": 0.0, "energyAutoconsuming": 1.62,
"batteryCycletime": 7}}]}, "success": true}}
2022-07-22 13:18:52 DEBUG (MainThread)
[custom_components.zcsazzurro.sensor] Return the state: True
2022-07-22 13:18:52 DEBUG (MainThread)
[custom_components.zcsazzurro.sensor] Return the state attributes

Ho provato a mettere maiuscola anche la lettera del nome, riavviato e ora
pare che i dati arrivino, ma se guardi la f0to allegata mi dice che le
entità non sono disponibili. scusa se sono una frana e ti rompo, non
accadra più una volta che sistemo

Il giorno ven 22 lug 2022 alle ore 13:12 sdesalve ***@***.***>
ha scritto:

**Comment by sdesalve** [comment]
Posta configurazione e codice Lovelace

Probabilmente il nome del sensore dichiarato non è lo stesso di Lovelace

**Comment by luca320** [comment]
##### current
template:
  - sensor:
      - name: "Potenza Istantanea"
        unit_of_measurement: "W"
        state: >
          {% set power =
state_attr('sensor.zcsazzurro','current')['powerGenerating'] | int(0) %}
          {{ power }}
        state_class: measurement
        device_class: power
        icon: mdi:solar-power

      - name: "Batteria"
        unit_of_measurement: "%"
        state: >
          {% set energy =
state_attr('sensor.zcsazzurro','current')['batterySoC'] | float(0) %}
          {{ energy | round(2) }}
        state_class: measurement
        device_class: energy
        icon: mdi:battery-90

      - name: "Consumo Giorno Casa"
        unit_of_measurement: "kWh"
        state: >
          {% set energy =
state_attr('sensor.zcsazzurro','current')['energyConsuming'] | float(0) %}
          {{ energy | round(2) }}
        state_class: measurement
        device_class: energy
        icon: mdi:power-socket-it

      - name: "Autoconsum Giorno"
        unit_of_measurement: "kWh"
        state: >
          {% set energy =
state_attr('sensor.zcsazzurro','current')['energyAutoconsuming'] | float(0)
%}
          {{ energy | round(2) }}
        state_class: measurement
        device_class: energy
        icon: mdi:power-plug-outline

      - name: "Scarica"
        unit_of_measurement: "kWh"
        state: >
          {% set energy =
state_attr('sensor.zcsazzurro','current')['energyDischarging'] | float(0) %}
          {{ energy | round(2) }}
        state_class: measurement
        device_class: energy
        icon: mdi:battery-low

      - name: "Carica"
        unit_of_measurement: "kWh"
        state: >
          {% set energy =
state_attr('sensor.zcsazzurro','current')['energyCharging'] | float(0) %}
          {{ energy | round(2) }}
        state_class: measurement
        device_class: energy
        icon: mdi:battery-high

      - name: "Produzione"
        unit_of_measurement: "kWh"
        state: >
          {% set energy =
state_attr('sensor.zcsazzurro','current')['energyGenerating'] | float(0) %}
          {{ energy | round(2) }}
        state_class: measurement
        device_class: energy
        icon: mdi:solar-power

      - name: "Prelievo"
        unit_of_measurement: "kWh"
        state: >
          {% set energy =
state_attr('sensor.zcsazzurro','current')['energyImporting'] | float(0)%}
          {{ energy | round(2) }}
        state_class: measurement
        device_class: energy
        icon: mdi:transmission-tower

      - name: "Immissione"
        unit_of_measurement: "kWh"
        state: >
          {% set energy =
state_attr('sensor.zcsazzurro','current')['energyExporting'] | float (0) %}
          {{ energy | round(2) }}
        state_class: measurement
        device_class: energy
        icon: mdi:solar-power

##### total
      - name: "Produzione Totale"
        unit_of_measurement: "kWh"
        state: >
          {% set energy =
state_attr('sensor.zcsazzurro','total')['energyGenerating'] | float(0) %}
          {{ energy | round(2) }}
        state_class: total_increasing
        device_class: energy
        icon: mdi:weather-sunny

      - name: "Prelievo Totale"
        unit_of_measurement: "kWh"
        state: >
          {% set energy =
state_attr('sensor.zcsazzurro','total')['energyImporting'] | float (0) %}
          {{ energy | round(2) }}
        state_class: total_increasing
        device_class: energy
        icon: mdi:transmission-tower

      - name: "Immissione Totale"
        unit_of_measurement: "kWh"
        state: >
          {% set energy =
state_attr('sensor.zcsazzurro','total')['energyExporting'] | float(0) %}
          {{ energy | round(2) }}
        state_class: total_increasing
        device_class: energy
        icon: mdi:flash-circle

      - name: "Autoconsum Totale"
        unit_of_measurement: "kWh"
        state: >
          {% set energy =
state_attr('sensor.zcsazzurro','total')['energyAutoconsuming'] | float(0) %}
          {{ energy | round(2) }}
        state_class: total_increasing
        device_class: energy
        icon: mdi:power-plug-outline

      - name: "Scarica Totale"
        unit_of_measurement: "kWh"
        state: >
          {% set energy =
state_attr('sensor.zcsazzurro','total')['energyDischarging'] | float(0) %}
          {{ energy | round(2) }}
        state_class: total_increasing
        device_class: energy
        icon: mdi:battery-low

      - name: "Carica Totale"
        unit_of_measurement: "kWh"
        state: >
          {% set energy =
state_attr('sensor.zcsazzurro','total')['energyCharging'] | float(0) %}
          {{ energy | round(2) }}
        state_class: total_increasing
        device_class: energy
        icon: mdi:battery-high


type: entities
entities:
  - entity: sensor.potenza_istantanea
  - entity: sensor.batteria
  - entity: sensor.consumo_giorno_casa
  - entity: sensor.autoconsum_giorno
  - entity: sensor.autoconsum_totale
  - entity: sensor.scarica_totale
  - entity: sensor.scarica_totale
  - entity: sensor.scarica
  - entity: sensor.power_generating_spent_zcs
  - entity: sensor.total_energy_exporting_zcs
  - entity: sensor.total_energy_generating_zcs
  - entity: sensor.total_energy_importing_zcs

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno ven 22 lug 2022 alle ore 14:14 sdesalve ***@***.***>
ha scritto:

**Comment by luca320** [comment]
È questo?! Se si sostituisco in yaml tutti i sensor.azzurrozcs con questo?

Inviato da iPhone

**Comment by sdesalve** [comment]
Questa è la definizione del sensore 


![Screenshot_2022-07-22-15-36-57-256_com android chrome](https://user-images.githubusercontent.com/9841662/180450778-ba45a5b4-7fed-469d-a7b8-bf69fed99ebf.jpg)

**Comment by sdesalve** [comment]
Qua si chiama fotovoltaico, quindi devi aggiornare i tuoi sensori

{% set energy =
state_attr('sensor.fotovoltaico','total')['energyDischarging'] | float(0) %}
