### ISSUE TITLE
Produzione istantanea

### ISSUE THREAD

**Issue by luca320** [sdesalve/zcsazzurro#15]
Ciao, come mai non si possono inserire i sensori della produzione istantanea nel pannello energia di HA?!

[image](https://user-images.githubusercontent.com/63425880/180602272-8480ba74-ad06-498a-89e3-a3e994646702.jpeg)

**Comment by lexlutor72** [comment]
Ho tentato anche io ma mi da qualche errore. Tra l'altro da ieri non sto più ricevendo dati. A te funziona tutto?

**Comment by Corrado56** [comment]
> Ciao, come mai non si possono inserire i sensori della produzione istantanea nel pannello energia di HA?!

Il pannello ENERGIA (o meglio "lavoro", unità di misura kWh) deduce i valori orari per differenza tra valori di energia crescenti  ad orari differenti.
E concettualmente errato passare al pannello energia valori di potenza (unita di misura W). Il pannello energia non calcola integrali.

La scelta rimane tra energia giornaliera (che si resetta ogni giorno) e energia totale.
Se vuoi utilizzare i sensori di energia giornaliera li devi definire con  "state_class: total_increasing", non con state_class: measurement come negli esempi di sdesalve

La state_class: total_increasing resetta automaticamente i progressivi dei totali quando il valore del totale diminuisce, il che avviene alla prima lettura dopo la mezzanotte, se usi i valori di energia giornaliera

**Comment by Corrado56** [comment]
https://developers.home-assistant.io/docs/core/entity/sensor#available-state-classes

E questo è un link alla documentazione

**Comment by luca320** [comment]
Corrado56 ti ringrazio, la tua spiegazione, seppur semplice, non è stata per me di facile comprensione. Mi ci sto addentrando e sto provando a studiacchiare, ma è evidente che sono ancora in alto mare. 
Quindi devo fare delle modifiche al configuration.yaml fornito dall'autore per poter poi utilizzare i sensori nel pannello energia? Oppure ne genero un paio di nuovi cambiando state class?

**Comment by Corrado56** [comment]
> Quindi devo fare delle modifiche al configuration.yaml

Si

Per esempio:

- name: "Consumo Giorno Casa"
        unit_of_measurement: "kWh"
        state: >
          {% set energy = state_attr('sensor.fotovoltaico','current')['energyConsuming'] | float(0) %}
          {{ energy | round(2) }}
--        state_class: measurement  -- Non si può usare nel pannello energia
        **state_class: total_increasing** -- Si può utilizzare
        device_class: energy
        icon: mdi:power-socket-it 

L'ipotesi è che il consumo sia un valore sempre crescente durante il giorno.

**Comment by luca320** [comment]
Grazie!! 
Idem per la produzione dei pannelli immagino

Inviato da iPhone

**Comment by Corrado56** [comment]
> Idem per la produzione dei pannelli immagino

Per tutte le entità che rappresentano un lavoro ( e non una potenza) e che durante il giorno aumentano costantemente puoi fare il cambio

**Comment by luca320** [comment]
Ciao Corrado, ho fatto le modifiche, le ho fatte anche per "carica" e
"scarica" delle batterie, ma mi dava valori di 500 kwh quindi immagino che
per le batterie si debba apportare una modifica diversa... se lascio la
configurazione così come è mi da questo errore che posto in foto
grazie ancora


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno lun 25 lug 2022 alle ore 15:02 sdesalve ***@***.***>
ha scritto:

**Comment by lexlutor72** [comment]
@Corrado56 Ciao. Potresti essere così gentile da farci un copia e incolla dei tuoi sensori, che poi adatteremmo al nostro HA, per verificare se sono corretti. Anche io rilevo valori strani. Vorrei attendere qualche giorno per avere un minimo di storico ma fare un riscontro sarebbe utile. Grazie.

**Comment by luca320** [comment]
> @Corrado56 Ciao. Potresti essere così gentile da farci un copia e incolla dei tuoi sensori, che poi adatteremmo al nostro HA, per verificare se sono corretti. Anche io rilevo valori strani. Vorrei attendere qualche giorno per avere un minimo di storico ma fare un riscontro sarebbe utile. Grazie. 

Eh sarebbe veramente interessante perché il mio pannello energia è inguardabile!!
![image](https://user-images.githubusercontent.com/63425880/180991207-7df1a165-e9b7-4ab2-9f00-edb08d445295.png)

**Comment by luca320** [comment]
> @Corrado56 Ciao. Potresti essere così gentile da farci un copia e incolla dei tuoi sensori, che poi adatteremmo al nostro HA, per verificare se sono corretti. Anche io rilevo valori strani. Vorrei attendere qualche giorno per avere un minimo di storico ma fare un riscontro sarebbe utile. Grazie.

Lexlutor72 ti posto i miei di sensori, ma qualcosa non va in energia... le batterie sono 0

template:
  - sensor:
      - name: "Potenza Istantanea"
        unit_of_measurement: "KWh"
        state: >
          {% set power = state_attr('sensor.fotovoltaico','current')['powerGenerating'] | int(0) %}
          {{ power }}
        state_class: measurement
        device_class: power
        icon: mdi:solar-power

      - name: "Batteria"
        unit_of_measurement: "%"
        state: >
          {% set energy = state_attr('sensor.fotovoltaico','current')['batterySoC'] | float(0) %}
          {{ energy | round(2) }}
        state_class: measurement
        device_class: energy
        icon: mdi:battery-90
        
#      - name: "Consumo Giorno Casa"
#        unit_of_measurement: "kWh"
#        state: >
#          {% set energy = state_attr('sensor.fotovoltaico','current')['energyConsuming'] | float(0) %}
#          {{ energy | round(2) }}
#        state_class: measurement 
#        device_class: energy
#        icon: mdi:power-socket-it
        
      - name: "Consumo Giorno Casa"
        unit_of_measurement: "kWh"
        state: >
          {% set energy = state_attr('sensor.fotovoltaico','current')['energyConsuming'] | float(0) %}
          {{ energy | round(2) }}
        state_class: total_increasing
        device_class: energy
        icon: mdi:power-socket-it         
        
#      - name: "Autoconsumo Giorno"
#        unit_of_measurement: "kWh"
#        state: >
#          {% set energy = state_attr('sensor.fotovoltaico','current')['energyAutoconsuming'] | float(0) %}
#          {{ energy | round(2) }}
#        state_class: measurement
#        device_class: energy
#        icon: mdi:power-plug-outline    

      - name: "Autoconsumo Giorno"
        unit_of_measurement: "kWh"
        state: >
          {% set energy = state_attr('sensor.fotovoltaico','current')['energyAutoconsuming'] | float(0) %}
          {{ energy | round(2) }}
        state_class: total_increasing
        device_class: energy
        icon: mdi:power-plug-outline 
        
#      - name: "Scarica"
#        unit_of_measurement: "kWh"
#        state: >
#          {% set energy = state_attr('sensor.fotovoltaico','current')['energyDischarging'] | float(0) %}
#          {{ energy | round(2) }}
#        state_class: total_increasing
#        device_class: energy
#        icon: mdi:battery-low 

      - name: "Scarica"
        unit_of_measurement: "kWh"
        state: >
          {% set energy = state_attr('sensor.fotovoltaico','current')['energyDischarging'] | float(0) %}
          {{ energy | round(2) }}
        state_class: measurement
        device_class: energy
        icon: mdi:battery-low 
        
      - name: "Carica"
        unit_of_measurement: "kWh"
        state: >
          {% set energy = state_attr('sensor.fotovoltaico','current')['energyCharging'] | float(0) %}
          {{ energy | round(2) }}
        state_class: measurement
        device_class: energy
        icon: mdi:battery-high
        
#      - name: "Carica"
#        unit_of_measurement: "kWh"
#        state: >
#          {% set energy = state_attr('sensor.fotovoltaico','current')['energyCharging'] | float(0) %}
#          {{ energy | round(2) }}
#        state_class: total_increasing 
#        device_class: energy
#        icon: mdi:battery-high         
        
#      - name: "Produzione"
#        unit_of_measurement: "kWh"
#        state: >
#          {% set energy = state_attr('sensor.fotovoltaico','current')['energyGenerating'] | float(0) %}
#          {{ energy | round(2) }}
#        state_class: measurement
#        device_class: energy
#        icon: mdi:solar-power

      - name: "Produzione"
        unit_of_measurement: "kWh"
        state: >
          {% set energy = state_attr('sensor.fotovoltaico','current')['energyGenerating'] | float(0) %}
          {{ energy | round(2) }}
        state_class: total_increasing
        device_class: energy
        icon: mdi:solar-power
        
#      - name: "Prelievo"
#        unit_of_measurement: "kWh"
#        state: >
#          {% set energy = state_attr('sensor.fotovoltaico','current')['energyImporting'] | float(0)%}
#          {{ energy | round(2) }}
#        state_class: measurement
#        device_class: energy
#        icon: mdi:transmission-tower  

      - name: "Prelievo"
        unit_of_measurement: "kWh"
        state: >
          {% set energy = state_attr('sensor.fotovoltaico','current')['energyImporting'] | float(0)%}
          {{ energy | round(2) }}
        state_class: total_increasing
        device_class: energy
        icon: mdi:transmission-tower 
        
#      - name: "Immissione"
#        unit_of_measurement: "kWh"
#        state: >
#          {% set energy = state_attr('sensor.fotovoltaico','current')['energyExporting'] | float (0) %}
#          {{ energy | round(2) }}
#        state_class: measurement
#        device_class: energy
#        icon: mdi:solar-power 

      - name: "Immissione"
        unit_of_measurement: "kWh"
        state: >
          {% set energy = state_attr('sensor.fotovoltaico','current')['energyExporting'] | float (0) %}
          {{ energy | round(2) }}
        state_class: total_increasing
        device_class: energy
        icon: mdi:solar-power
           
##### total         
      - name: "Produzione Totale"
        unit_of_measurement: "kWh"
        state: >
          {% set energy = state_attr('sensor.fotovoltaico','total')['energyGenerating'] | float(0) %}
          {{ energy | round(2) }}
        state_class: total_increasing
        device_class: energy
        icon: mdi:weather-sunny
        
      - name: "Prelievo Totale"
        unit_of_measurement: "kWh"
        state: >
          {% set energy = state_attr('sensor.fotovoltaico','total')['energyImporting'] | float (0) %}
          {{ energy | round(2) }}
        state_class: total_increasing
        device_class: energy
        icon: mdi:transmission-tower
        
      - name: "Immissione Totale"
        unit_of_measurement: "kWh"
        state: >
          {% set energy = state_attr('sensor.fotovoltaico','total')['energyExporting'] | float(0) %}
          {{ energy | round(2) }}
        state_class: total_increasing
        device_class: energy
        icon: mdi:flash-circle
        
      - name: "Autoconsum Totale"
        unit_of_measurement: "kWh"
        state: >
          {% set energy = state_attr('sensor.fotovoltaico','total')['energyAutoconsuming'] | float(0) %}
          {{ energy | round(2) }}
        state_class: total_increasing
        device_class: energy
        icon: mdi:power-plug-outline 
        
      - name: "Scarica Totale"
        unit_of_measurement: "kWh"
        state: >
          {% set energy = state_attr('sensor.fotovoltaico','total')['energyDischarging'] | float(0) %}
          {{ energy | round(2) }}
        state_class: total_increasing
        device_class: energy
        icon: mdi:battery-low
        
      - name: "Carica Totale"
        unit_of_measurement: "kWh"
        state: >
          {% set energy = state_attr('sensor.fotovoltaico','total')['energyCharging'] | float(0) %}
          {{ energy | round(2) }}
        state_class: total_increasing
        device_class: energy
        icon: mdi:battery-high

**Comment by lexlutor72** [comment]
Mi sembrano identici ai miei.
Ho problemi solo con il sensore della rete che non mi da il valore giornaliero ma mi riporta un valore totale che non so da dove lo prende.
Ti posto quelli delle mie batterie che sembra che vadano.


- name: "Scarica_pann_energia"
        unit_of_measurement: "kWh"
        state: >
          {% set energy = state_attr('sensor.fotovoltaico','current')['energyDischarging'] | float(0) %}
          {{ energy | round(2) }}
        state_class: total_increasing
        device_class: energy
        icon: mdi:battery-low 
        
      - name: "Carica_pann_energia"
        unit_of_measurement: "kWh"
        state: >
          {% set energy = state_attr('sensor.fotovoltaico','current')['energyCharging'] | float(0) %}
          {{ energy | round(2) }}
        state_class: total_increasing
        device_class: energy
        icon: mdi:battery-high

**Comment by luca320** [comment]
Ora provo a mettere nuovamente state_class: total increasing, ma ieri mi
dava valori assurdi tipo 500 KWh

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno mar 26 lug 2022 alle ore 21:32 lexlutor72 <
***@***.***> ha scritto:

**Comment by luca320** [comment]
Nel pannello energia hai inserito questi sensori? calcola che ancora non ho
il contatore per la reimmissione in rete perchè l'impianto è di qualche
settimana fa.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno mar 26 lug 2022 alle ore 21:32 lexlutor72 <
***@***.***> ha scritto:

**Comment by Corrado56** [comment]
> @Corrado56 Ciao. Potresti essere così gentile da farci un copia e incolla dei tuoi sensori...

1) Con i copia e incolla non si impara niente
2) le mie definizioni dei sensori le puoi trovare sul fork Corrado56/zcsazzurro
3) poiché nulla si crea né si distrugge, comincia a costruirti un qualcosa che ti dia il bilancio dell'energia giornaliera suddiviso tra fonti e impieghi (Fonti == Impieghi, se Fonti <> Impieghi hai sbagliato qualcosa)
![image](https://user-images.githubusercontent.com/10588158/181630036-94d258d2-1540-43ed-8949-4153270f9cef.png)
4) quando fonti == Impieghi, allora usa i sensori nel tab energia

**Comment by luca320** [comment]
Buongiorno, partendo dal presupposto che ho seguito le tue linee e i dati
forniti da ZCS sono corretti, ho un problema con il pannello energia di HA.
Succede che alla mattina mi trovo un prelievo dalla rete di circa 5-6 kwh,
cosa che assolutamente non accade e lo si vede anche dai dati che fornisce
zcs nell'integrazione che hai fornito. in configurazione energetica
inserisco i sensor carica e scarica, ma presumibilmente alla mezzanotte i
valori si azzerano e mentre a quell'ora io ho le batterie completamente
cariche è come se il sistema azzerasse tutto e con esso anche il livello di
carica delle batterie di accumulo. io credo che il sistema, non essendovi
di notte produzione energetica e trovando a zero (presuppongo
l'azzeramento) il livello delle batterie presupponesse che l'energia
consumata nella notte venga presa dalla rete elettrica. ovviamente andando
a vedere i dati di zcs su HA vedo che dalla rete non è stato prelevato
nulla, ma che il livello delle batterie sia calato del 50%, overo quei
famosi 5kwh che ilpannello energia mi segnala come presi dalla rete.
Spero di essermi spiegato sufficientemente bene. Idee?


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno gio 28 lug 2022 alle ore 22:22 Corrado56 ***@***.***>
ha scritto:
