### ISSUE TITLE
Interruzione ricezione dati.

### ISSUE THREAD

**Issue by lexlutor72** [sdesalve/zcsazzurro#16]
Da ieri, verso le 13,30 circa il mio HA non riceve più dati d ZCS. E' successo anche a voi? Qualcuno ha notizie in merito.

**Comment by sdesalve** [comment]
I log, dopo aver attivato il debug del componente REST, che dicono?

Senza info non è possibile sapere che sta succedendo

**Comment by Corrado56** [comment]
Confermo, qui sotto il tab energy con la produzione oraria di ieri 23/07 restituita dalla chiamata alle API
![image](https://user-images.githubusercontent.com/10588158/180653427-5065cdff-cf5f-417a-94af-ccd4c5dfde90.png)
Non è un problema di connessione. Piuttosto di database
![image](https://user-images.githubusercontent.com/10588158/180653911-c94eedd4-0dc8-465f-8150-5a4cd3e56b6f.png)

L'applicazione ZCS Azzurro su android non riceve dati 
ZCSAzzurro portal continua a funzionare

**Comment by asiviero76** [comment]
Ciao a tutti,
voi esperti sviluppatori ha mai provato a connettersi direttamente all'inverter? ho trovato una guida ma non riuscendo a fare il debug è difficile per me capirci qualcosa.... https://github.com/jlopez77/DeyeInverter  questo inverter è lo stesso ZCS e usa la stessa usb wifi stick...

**Comment by Corrado56** [comment]
Dopo un giorno e mezzo di interruzione adesso l'applicazione android restituisce un messaggio: "Dear customer, our server is under maintenance. Bla, bla, bla, we are sorry... "

Planned maintenance, I suppose...
