### ISSUE TITLE
Pannello energy HA - Batterie

### ISSUE THREAD

**Issue by luca320** [sdesalve/zcsazzurro#18]
Buongiorno, partendo dal presupposto che ho seguito le tue linee e i dati forniti da ZCS sono corretti, ho un problema con il pannello energia di HA. Succede che alla mattina mi trovo un prelievo dalla rete di circa 5-6 kwh, cosa che assolutamente non accade e lo si vede anche dai dati che fornisce zcs nell'integrazione che hai fornito. in configurazione energetica inserisco i sensor carica e scarica, ma presumibilmente alla mezzanotte i valori si azzerano e mentre a quell'ora io ho le batterie completamente cariche è come se il sistema azzerasse tutto e con esso anche il livello di carica delle batterie di accumulo. io credo che il sistema, non essendovi di notte produzione energetica e trovando a zero (presuppongo l'azzeramento) il livello delle batterie presupponesse che l'energia consumata nella notte venga presa dalla rete elettrica. ovviamente andando a vedere i dati di zcs su HA vedo che dalla rete non è stato prelevato nulla, ma che il livello delle batterie sia calato del 50%, overo quei famosi 5kwh che ilpannello energia mi segnala come presi dalla rete.
Spero di essermi spiegato sufficientemente bene. Idee?
![1](https://user-images.githubusercontent.com/63425880/183253860-66f43458-2f73-43e8-91d8-8812028029ba.jpg)
![2](https://user-images.githubusercontent.com/63425880/183253861-42a075b0-ef32-4d67-b212-9e53916407c3.jpg)
![3](https://user-images.githubusercontent.com/63425880/183253932-ce600e8a-00c9-45e1-a80f-df54d0cca012.jpg)

**Comment by sdesalve** [comment]
Invece di total_increasing prova a mettere measuring

**Comment by luca320** [comment]
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno sab 6 ago 2022 alle ore 17:04 sdesalve ***@***.***>
ha scritto:

**Comment by sdesalve** [comment]
Aspetta. Quale sensore viene incrementato anche quando consumi le batterie? 
Non è che i dati restituiti dalle Api non considerano la scarica delle batterie e vanno sottratti i consumi prelevati dalle batterie?

**Comment by luca320** [comment]
Sto parlando del solo pannello energia sia chiaro. Non dei dati che zcs fornisce che sono esatti. In sostanza nel pannello energia incrementa il prelievo della rete. È come se a mezzanotte si azzerasse la carica delle batterie quando invece sono al 90% e quando questo succede i consumi che ho di notte il pannello energia me li scarica dalla rete anziché dalle batterie. Se concludo la giornata con il90% di batterie cariche, a mezzanotte il sensore batterie anziché indicare che sono cariche al 90% presumo parta da zero

Inviato da iPhone

**Comment by luca320** [comment]
C’è una bella differenza tra i dati di zcs e quelli del pannello energia


Inviato da iPhone

**Comment by sdesalve** [comment]
Allora quel valore considera la corrente in uscita dalli'nverter. Devi sottrarre la scarica della batteria per sapere quanto hai assorbito dalla rete

Da quanto dici pare che non consideri in automatico quanto prende dalle batterie ma solo quello che eroga, come se non fosse prevista questa funzionalità.

Prova a sentire ZCS per chiedergli se, di notte durante la scarica delle batterie, il valore di
current' energyImporting riporta quanto assorbito dalla sola rete o anche dalle batterie

**Comment by Corrado56** [comment]
Per quel che mi risulta, tutti i valori di current.energy si resettano a 0 alla mezzanotte.
per esempio, questa è l'energia immessa in rete che vedo io
![image](https://user-images.githubusercontent.com/10588158/184532116-58b0fba0-f08f-45d0-a1c9-b7a4dd922036.png)

E nella configurazione del pannello energia si usano solo dati di energia. 
Non capisco i riferimenti a cicli di carica o percentuali di carica.
"Trovando a 0 la percentuale di carica" >> la percentuale di carica non viene passata al pannello energia, ed inoltre non è di tipo total_increasing, quindi non si resetta 
![image](https://user-images.githubusercontent.com/10588158/184532431-c77d6fff-d7f2-4fcf-bc46-5a01d5397bac.png)


Inoltre c'è una tolleranza di 100W nella regolazione dell'inverter, per cui può prelevare da 0 a 100W in qualsiasi momento, prima di intervenire a cambiare la propria regolazione.
per esempio, questa è l'energia prelevata dalla rete, e come vedi c'è un prelievo anche alle 4 del mattino a batterie cariche
![image](https://user-images.githubusercontent.com/10588158/184532233-97fc01d3-cc82-4e76-8142-304d339d1a42.png)


Questa è la mia configurazione del pannello energia, che da me funziona, al netto delle tolleranze. Vengono passati 5 valori di current.energy tutti di tipo total_increasing
![image](https://user-images.githubusercontent.com/10588158/184532065-04443625-8306-4638-9af3-a9121e7c8166.png)
