### ISSUE TITLE
error sensor.zcsazzurro - cannot import name 'STATE_CLASS_MEASUREMENT'

### ISSUE THREAD

**Issue by tuxape** [sdesalve/zcsazzurro#2]
Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:454
Integration: Hass.io (documentation, issues)
First occurred: 6:17:51 PM (1 occurrences)
Last logged: 6:17:51 PM

Platform error sensor.zcsazzurro - cannot import name 'STATE_CLASS_MEASUREMENT' from 'homeassistant.components.sensor' (/usr/src/homeassistant/homeassistant/components/sensor/__init__.py)

**Comment by sdesalve** [comment]
HomeAssistant version? Host system?

**Comment by tuxape** [comment]
Home Assistant Core
Version
core-2021.3.3
Newest Version
core-2021.11.3
 
Operating System
Version
6.4
Newest Version
6.6

**Comment by sdesalve** [comment]
you MUST upgrade your Hassio to latest available to use this custom component.
Sensors rely on STATE_CLASS_MEASUREMENT that was introduced recently

**Comment by tuxape** [comment]
thank you
