### ISSUE TITLE
Installazione

### ISSUE THREAD

**Issue by federicacantone** [sdesalve/zcsazzurro#21]
Ciao,
Vorrei integrare il mio zucchetti zcs con home assistant ma non capisco dove trovare le 2 delle 3 info che richiede il tuo addon
Conosco solo il serial number.
Dove posso trovare authkey e  clientcode ?
Hai un manuale?
Grazie mille e buon anno!!!

**Comment by sdesalve** [comment]
Ciao Federica, 
devi inviare una mail [service.azzurrozcs@zcscompany.com](mailto:service.azzurrozcs@zcscompany.com)
e chiedere l’accesso alle API.
Ti invieranno un pdf con il clientcode e l'authkey da abbinare al tuo serial number (thingkey).

Buon anno

**Comment by federicacantone** [comment]
Ciao,
Ho chiesto le info ma mi hanno fornito solo il codice cliente con delle specifiche API ver 1.5 datate al 24-10-2022.
è cambiato qualcosa o devo chiedere anche authkey?

Ho allegato il documento ricevuto.
Grazie mille!
Fede


[Specifica API 1.5 del 24-10-2022 (IT).docx](https://github.com/sdesalve/zcsazzurro/files/10340301/Specifica.API.1.5.del.24-10-2022.IT.docx)

**Comment by sdesalve** [comment]
Non è cambiato nulla. Mandami una mail e ti mando l'authkey, tanto è uguale per tutti 

Pare abbiano fatto in modo che per i vecchi utenti sia necessaria l'authkey mentre per i nuovi il clientcode

**Comment by federicacantone** [comment]
fatto grazie
