### ISSUE TITLE
missing ID

### ISSUE THREAD

**Issue by MartinMcFlyITA** [sdesalve/zcsazzurro#22]
Hi 
using your integration I can't see any data from zcs api endpoint.

Each entity report an issue (missing ID)

kind regards
<img width="1602" alt="Screenshot 2023-01-09 alle 12 28 43" src="https://user-images.githubusercontent.com/17080368/211298672-7fdda76a-01e4-44a0-923a-e9d3d66e4615.png">

**Comment by sdesalve** [comment]
Is not an issue! Every entity added manually don't have an id...

Enable debug and post here configuration/logs

https://github.com/sdesalve/zcsazzurro/issues/20#issuecomment-1365909042

**Comment by MartinMcFlyITA** [comment]
Ciao Salvatore

so don't worry about me, your integration works like a charm :) :)

thanks 4 ur help
M
