### ISSUE TITLE
Confronto Solarman (via wiFi dongle) - DeSalve (via API)

### ISSUE THREAD

**Issue by Corrado56** [sdesalve/zcsazzurro#26]
Sto confrontando l'integrazione solarman (via wifi dongle) con quella desalve (via API)
1) Energia totale (le immagini sono prese a circa due ore di distanza)
![image](https://user-images.githubusercontent.com/10588158/230714623-5f540c44-1798-412e-9299-5b205aac9642.png)
C'è una anomalia nei valori di consumo, che non so spiegare
2) Energia giornaliera
![image](https://user-images.githubusercontent.com/10588158/230714692-cbe27184-1cc5-4bb7-813a-fb348aeb35aa.png)
posso garantire che subito dopo l'aggiornamento via API i valori corrispondono
3) Potenza
![image](https://user-images.githubusercontent.com/10588158/230714750-06ba5132-40b2-435a-9c2e-54b3a3b1ebf8.png)
Qui, mentre le api espongono due valori distinti per carico e scarico batterie e rete, solarman espone un unico valore con segno. (+ carica batterie - scarica batterie )
4) Con solarman è possibile monitorare molte più grandezze. In particolare la temperatura. Attualmente sto caricando 3kw, e si vede.
![image](https://user-images.githubusercontent.com/10588158/230714862-a502e994-647d-4174-a639-2008d02eea56.png)
5) Solarman è più affidabile e si aggiorna ogni 2 secondi. Zucchetti ha altri pensieri.

Detto questo, c'è qualcuno con più esperienza di me che mi spiega come scrivere un template con una IF in mezzo per ottenere due valori distinti per carica e scarica batterie ?

Corrado Cavallini

**Comment by sdesalve** [comment]
Non è una issue...sulla community di HomeAasistant ho un thread e c'è pure un gruppo telegram in cui chiedere aiuto. Oppure c'è Google per info su come creare i template
