### ISSUE TITLE
Unable to start fetching data from ZCSAzzurro

### ISSUE THREAD

**Issue by demaiopacido** [sdesalve/zcsazzurro#4]
## System Health
version | core-2021.12.10
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.91
arch | x86_64
timezone | Europe/Rome

GitHub API | ok

host_os | Home Assistant OS 7.2
update_channel | stable
supervisor_version | supervisor-2021.12.2
docker_version | 20.10.9
disk_total | 31.3 GB
disk_used | 3.8 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok

Inseriti correttamente 
thingkey: "ZMxxxxxxxx"
authkey: "Zxx xxxxxxx0"
il sensore test_zcsazzurro restituisce valore true 
tutti gli altri  i paramentri risultano non disponibili

il registro restituisce i seguenti errori :
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.zcsazzurro.sensor
Source: custom_components/zcsazzurro/sensor.py:250
Integration: zcsazzurro (documentation, issues)
First occurred: 16:40:05 (1 occurrences)
Last logged: 16:40:05

**Unable to start fetching data from ZCSAzzurro**

Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.zcsazzurro.sensor
Source: custom_components/zcsazzurro/sensor.py:343
Integration: zcsazzurro (documentation, issues)
First occurred: 16:40:05 (4 occurrences)
Last logged: 16:53:14

**Empty reply found when expecting JSON data**

**Comment by sdesalve** [comment]
Empty reply found when expecting JSON data

I server di ZCS non hanno risposto correttamente. Please retry and wait for a correct response

**Comment by demaiopacido** [comment]
Grazie, Great Job !
