### ISSUE TITLE
Problem update data since yesterday

### ISSUE THREAD

**Issue by dicemans** [sdesalve/zcsazzurro#9]
Hello,
since yesterday i can no longer receive data correctly from the zcs cloud. 
Does it happen to you too or is it just my problem? 
thx for support

```
Template variable error: 'homeassistant.util.read_only_dict.ReadOnlyDict object' has no attribute 'total' when rendering '{% set energy = states.sensor.test_zcsazzurro.attributes.total.energyImporting | float | default (0) %} {{ energy | round(2) }}'
10:32:43 – (ERRORE) helpers/template.py - il messaggio si è verificato per la prima volta alle 09:21:43 e compare 1095 volte

TemplateError('UndefinedError: 'homeassistant.util.read_only_dict.ReadOnlyDict object' has no attribute 'total'') while processing template 'Template("{% set energy = states.sensor.test_zcsazzurro.attributes.total.energyImporting | float | default (0) %} {{ energy | round(2) }}")' for attribute '_attr_native_value' in entity 'sensor.prelievo_totale'
09:21:43 – (ERRORE) Template - il messaggio si è verificato per la prima volta alle 09:21:43 e compare 15 volte

Error while processing template: Template("{% set energy = states.sensor.test_zcsazzurro.attributes.total.energyImporting | float | default (0) %} {{ energy | round(2) }}")
09:21:43 – (ERRORE) helpers/template.py - il messaggio si è verificato per la prima volta alle 09:21:43 e compare 15 volte
```

**Comment by demaiopacido** [comment]
You are not alone!!
Same problem since yesterday

**Comment by sdesalve** [comment]
Please ask ZCS if they had changed something...

If postman doesn't recognize thingkey is there a problem their side...

**Comment by Corrado56** [comment]
I think thingkey is recognized and also authkey. 
If I change authkey the response is "not authenticated"
I sent a request to ZCS assistance and will update this thread when I receive any answer

**Comment by aturri** [comment]
Me too, the same problem since yesterday. I contacted ZCS assistance, let's see...

**Comment by aturri** [comment]
Does anyone have any news?

**Comment by superino1** [comment]
> Does anyone have any news?

No, same problem. Send mail to Zcs, but no answer.

**Comment by dicemans** [comment]
Support answered me to this:

```
Good morning,
to use the API requests it is necessary to provide an authorization code and a customer code. The latter, provided in the previous email ('xxxxxxxxxx'), has become mandatory for a week and must be entered at the time of the request.

Sincerely
```

I hope it will be useful to the developer

**Comment by sdesalve** [comment]
> 

Please ask they the updated API documentation so I can update custom component

**Comment by aturri** [comment]
Hi,
I have found that it is necessary the header "Client" with the client code that was sent you by email.
<img width="832" alt="Screenshot 2022-06-29 at 18 50 49" src="https://user-images.githubusercontent.com/6987093/176492535-af5e64b3-85e3-4b37-bb35-fcbcce223cf6.png">

In this way, I'm using the API correctly with Postman.

Thank you
Andrea

**Comment by sdesalve** [comment]
please update to v3.0.0.
YOU WILL NEED to update your sensor definition.

thanks to @aturri

**Comment by sdesalve** [comment]
You must ask to zcs your **clientcode**. They had started to send within the mail with apikey only recently....

**Comment by spady7** [comment]
> You must ask to zcs your **clientcode**. They had started to send within the mail with apikey only recently....

Thank you for reply. I supposed that ZCS had to send me clientcode. What i needed was to know how configure your custom component. Anyway, having a look to "sensor.py" i realized that i have to add 'clientcode: "" ' .
Hope can help this someone else.

Regards

**Comment by sdesalve** [comment]
> Anyway, having a look to "sensor.py" i realized that i have to add 'clientcode: "" ' .

Yep it's stated in changelog... 

![image](https://user-images.githubusercontent.com/9841662/176721054-fc44fc54-97d7-4de4-87b5-8b469c2d8803.png)
